### ISSUE TITLE
Add This Please

### ISSUE THREAD

**Issue by ItsMeRioooo** [SneakyHub/discord-js-community-bot#20]
const koenie06games = require('koenie06-games')

const TicTacToe = new koenie06games.TicTacToe()
const ConnectFour = new koenie06games.ConnectFour()
const HangMan = new koenie06games.HangMan()
const SnakeGame = new koenie06games.SnakeGame()
const FastTyper = new koenie06games.FastTyper()
const guessTheNumber = new koenie06games.GuessTheNumber()
const RockPaperScissors = new koenie06games.RockPaperScissors()

client.on('ready', () => {

    console.log(`I'm online!`)

})

client.on('message', async message => {

    if(message.content.startsWith('!tictactoe')) {

        TicTacToe.newGame(message)

    }

    if(message.content.startsWith('!connectfour')) {

        ConnectFour.newGame(message)
        
    }

    if(message.content.startsWith('!hangman')) {

        HangMan.newGame(message)
        
    }

    if(message.content.startsWith('!snakegame')) {

        SnakeGame.newGame(message)
        
    }

    if(message.content.startsWith('!fasttyper)) {

        FastTyper.newGame(message)
        
    }

    if(message.content.startsWith('!guessthenumber)) {

        guessTheNumber.newGame(message)

    }

    if(message.content.startsWith('!rockpaperscissors)) {

        RockPaperScissors.newGame(message)
        
    }

})

**Comment by carlromulo** [comment]
nab
it has errors

**Comment by carlromulo** [comment]
missing (') at the rockpaperscissors, guessthenumber and fastTyper

**Comment by Microwave-6443** [comment]
next time leave a pull request :)
