### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by SneakyHub** [SneakyHub/discord-js-community-bot#8]
Add More Moderation Commands

**Account Checker**:

- check accounts if they are brand new or not. If they are new then dm them saying they was banned for having a brand new account and then have the server ban them.

**Anti Raid Features**:
- lockdown ( in case we do get raided )
- unlockdown ( backs us out of lockdown )
- slowmode ( updates all public text channels to a slowmode that we specify but must remember their previous slowdown interval )

**Community Features**:

- meme ( meme command )
- invites ( track invites )
- dog ( gets a random image of a doggo )
- cat ( gets a random image of a cat )
- 8ball ( idk how to word this but you get the idea )

**Comment by Microwave-6443** [comment]
I'll look into it :)

**Comment by Microwave-6443** [comment]
lockdown/unlockdown added: `?lockdown <set/remove> <#channel or it will default to the channel the message is in>`
slowmode added: `?slowmode <slowmode in seconds>`

**Comment by Microwave-6443** [comment]
dog: api needed
cat: api needed
meme: use reddit maybe?
8ball: working on it
invite tracker: gonna take more time to make

**Comment by Microwave-6443** [comment]
most of this is done

**Comment by SneakyHub** [comment]
> 
> 
> most of this is done

What exactly is completed from this list?

**Comment by TheUsual10k** [comment]
> dog: api needed
> cat: api needed
> meme: use reddit maybe?
> 8ball: done
> invite tracker: gonna take more time to make

use somerandomapi for dog and cat api , ill make a pull request to it if you want?

**Comment by SneakyHub** [comment]
> 
> 
> > dog: api needed
> > cat: api needed
> > meme: use reddit maybe?
> > 8ball: done
> > invite tracker: gonna take more time to make
> 
> use somerandomapi for dog and cat api , ill make a pull request to it if you want?

You can add the dog and cat api if you want :)
