### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by Microwave-6443** [SneakyHub/discord-js-community-bot#9]
- Anti-Spam
- Invite Tracker
- Ticket System(done)

More will be added.

**Comment by SneakyHub** [comment]
Ticket system seems to be more of a priority. Then anti spam then invite tracker. If we could have all data stored in a mongodb that would be great :)

**Comment by Microwave-6443** [comment]
I need to fix the member join system, the code for kicking them if their account is under 28 days old is missing.

**Comment by Microwave-6443** [comment]
- Better configuration ability
- MongoDB integration (switching Quick.DB with MongoDB)
- code changes (documentation etc)

**Comment by Microwave-6443** [comment]
leaderboard integration

**Comment by Microwave-6443** [comment]
update everything

**Comment by Microwave-6443** [comment]
the server configs still needs to be integrated with MongoDB, currently the configs are basically hard coded which makes it hard to configure for anyone attempting to use the application
